language: node_js
node_js:
  - "6"
  - "8"
  - "10"
cache:
  directories:
    - "node_modules"
before_script:
  - npm run devBuild
script:
  - npm t
after_success: 
  - npm run coveralls
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: "leo@furze-waddock.com"
  api_key: 
    secure: $npm_access_token
  on:
    tags: true