language: node_js
node_js:
  - "8"
  - "10"
  - "12"
cache:
  directories:
    - "node_modules"
before_script:
  - npm run devBuild
script:
  - npm t
after_success:
  - npm run coveralls
before_deploy:
  - npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: "leo@furze-waddock.com"
  api_key:
    secure: $npm_access_token
  on:
    tags: true
